services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mssql
    hostname: mssql
    restart: unless-stopped
    ports:
      - 1433:1433
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
  
  webapi:    
    container_name: coffeecard-fuzzing
    image: "zeller24/fuzzingbook"
    depends_on:
      mssql:
        condition: service_healthy
    command: sleep infinity
    volumes:
      - ..:/workspace
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DatabaseSettings__ConnectionString=Server=mssql;Initial Catalog=master2;User=sa;Password=Your_password123;TrustServerCertificate=True;